image: debian:stretch

before_script:
  - apt update -qq
  - apt install --no-install-recommends -y gcc make autoconf automake libtool

stages:
  - autogen
  - build
  - test

autogen:
  stage: autogen
  script: ./autogen && ./configure

build:
  stage: build
  script: make

test:
  stage: test
  script: make check
